name: code-checks
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: "**/setup.cfg"
      - run: pip install -e .[test,mypy]
      - run: mypy jsonargparse*/*.py
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: "**/setup.cfg"
      - run: pip install -e .[all,test,pylint]
      - run: pylint --rcfile=setup.cfg jsonargparse*/*.py
